name: ci_python

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: sudo apt install -yq --no-install-recommends gfortran
    - run:  pip install -e .[tests,lint]
    - run: flake8
    - run: mypy .
    - run: pytest -r a -v

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc
    - run: pip install -e .[tests]
    - run: pytest -r a -v

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg
      shell: powershell
    - run: pip install -e .[tests]
    - run: pytest -r a -v


  install:
    needs: [linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: sudo apt install -yq --no-install-recommends gfortran
    - run: python setup.py install
    - name: install test
      run: |
        cd ${HOME}
        python -m pip install pytest
        python -m pytest ${GITHUB_WORKSPACE} -r a -v